### ISSUE TITLE
Incompatibility with CIT Resewn textures in Inventory

### ISSUE THREAD

**Issue by Azureblooet** [Theoness1/EatingAnimation#21] opened 2022-06-03 02:38 UTC
I've seen this bug reported with Optifine/Optifabric to a but to report it in a more concise way, I'll do so here.

As far as I've seen, CIT replacements are bugged in the inventory.
Strangely enough, they seem to render with their appropriate cit textures elsewhere.
Screenshots demonstrating this are below: (if it works)

![image](https://user-images.githubusercontent.com/88201702/171774134-64db071d-65cb-4882-99b4-9693472b77e9.png)

![image](https://user-images.githubusercontent.com/88201702/171775122-1db4f269-ce93-4733-a506-6abbe9daee8b.png)

![image](https://user-images.githubusercontent.com/88201702/171775729-4c22ec2b-445e-4587-873c-b26d6b90fcbb.png)

the Redstone in the Hotbar appears with the regular default texture,  however, In the player's hand (both first and third person), and  as a dropped item, the texture changes following the CIT of the resource pack

additionally, and possibly related, food animations also don't render in the inventory.
through basic testing, the type of CIT doesn't appear to matter, just the fact that the item has changed.

**Comment by Theoness1** [comment] 2022-06-03 05:43
Thanks for screenshots

**Comment by Theoness1** [comment] 2022-06-03 05:52
CIT reserwn adds such a pouch or what is it?

**Comment by Julienraptor01** [comment] 2022-06-03 06:19
Not they simply use a pack that has CIT in it
This is a duplicate of #9 and #20
It can partially be resolved by #16

**Comment by Julienraptor01** [comment] 2022-06-03 06:20
This is a duplicate of #9

**Comment by Theoness1** [comment] 2022-07-21 19:36
fixed soon

**Closed as completed by Theoness1** 2022-07-21 19:36 UTC
