### ISSUE TITLE
EatingAnimation mod breaks potion CIT (Optifine)

### ISSUE THREAD

**Issue by TheSweatyYeti** [Theoness1/EatingAnimation#9] opened 2021-10-27 06:26 UTC
If you have a resource pack that adds CIT (Custom Item Textures) to potions using Optifine, the potions in the GUI will not use the CIT provided by the resource pack. The potions held in the players hands, on the ground, and in item frames will use the CIT, but in the inventory, they will not.

The mod doesn't effect all CIT. As shown in the clips, CIT for axolotl buckets are unaffected.

I'm unsure why the mod breaks potion CIT considering the mod doesn't give potions a drinking animation.

**Videos:**
[Without EatingAnimations mod.](https://streamable.com/5tlztz)
[With EatingAnimations mod.](https://streamable.com/i8ocwj)

**Comment by bbharier** [comment] 2021-11-09 05:03
I too am having this issue. Installing the Eating Animation mod makes Potion and Enchanted Book resource pack textures get overridden back to their defaults. 

Here’s some examples of CIT packs that break with Eating Animation installed alongside CIT Resewn: 
https://www.curseforge.com/minecraft/texture-packs/xalis-enchanted-books
https://www.curseforge.com/minecraft/texture-packs/xalis-potions

**Comment by Theoness1** [comment] 2021-11-09 07:46
> If you have a resource pack that adds CIT (Custom Item Textures) to potions using Optifine, the potions in the GUI will not use the CIT provided by the resource pack. The potions held in the players hands, on the ground, and in item frames will use the CIT, but in the inventory, they will not.
> 
> The mod doesn't effect all CIT. As shown in the clips, CIT for axolotl buckets are unaffected.
> 
> I'm unsure why the mod breaks potion CIT considering the mod doesn't give potions a drinking animation.
> 
> **Videos:** [Without EatingAnimations mod.](https://streamable.com/5tlztz) [With EatingAnimations mod.](https://streamable.com/i8ocwj)

Can you send a video not through this site?

**Comment by TheSweatyYeti** [comment] 2021-11-09 07:59
> Can you send a video not through this site?

Why? What's wrong with this site? What site do you want me to use if you don't want that website in particular?

**Comment by Theoness1** [comment] 2021-11-09 08:00
> > Can you send a video not through this site?
> 
> Why? What's wrong with this site? What site do you want me to use if you don't want that website in particular?

This site does not open, maybe due to the fact that I am in another country ))

**Comment by Theoness1** [comment] 2021-11-10 08:33
> I had some report too of people having some issue with xali's potions and your mod which is a bummer. I looked into your assets to add compatibility but nothing seems to touch the potions so I'm not entirely certain why the issue is. There is around 3 or 4 people on my discord that came to me with that issue. But this seems to be applied to every CIT texture in the GUI. Nowhere else.

It turns out the problem is somewhere in CIT ?

**Comment by TheSweatyYeti** [comment] 2021-11-18 06:18
> This site does not open, maybe due to the fact that I am in another country ))

Try this then.
It's definitely something with your mod.

[Without EatingAnimations mod.](https://vimeo.com/647181517)
[With EatingAnimations mod.](https://vimeo.com/647179638)

**Comment by SHsuperCM** [comment] 2021-11-22 03:36
This is probably a duplicate of #2

**Comment by TheSweatyYeti** [comment] 2021-11-27 09:58
lol I'll pretend I understood any of what you just said and take your word for it

**Comment by SHsuperCM** [comment] 2021-11-27 10:01
> lol I'll pretend I understood any of what you just said and take your word for it


Apologies, it was meant for the dev.

**Comment by TheSweatyYeti** [comment] 2021-11-27 10:22
> Apologies, it was meant for the dev.

lol fair enough. Better they get it and understand it than me

**Comment by Gabo6480** [comment] 2022-01-02 22:18
Having the same problem with: https://www.curseforge.com/minecraft/texture-packs/visual-enchantments
The items on the player inventory do not show the CIT

**Comment by TheDerpu0ne** [comment] 2022-01-22 19:48
I have the issue too, I am using Xali's Potions and EatingAnimation and it just shows the vanilla textures.

**Comment by Felix14-v2** [comment] 2022-02-12 11:56
Can confirm, I have the same issue, but with Fabric [CIT Resewn](https://github.com/SHsuperCM/CITResewn) mod.

**Comment by TheSweatyYeti** [comment] 2022-02-20 07:19
> Can confirm, I have the same issue, but with Fabric [CIT Resewn](https://github.com/SHsuperCM/CITResewn) mod.

Interesting. So it definitely isn't an Optifine issue. It must definitely be an issue with this mod. Good to know.

**Comment by EGOIST1372** [comment] 2022-05-18 12:47
@Theoness1 @SHsuperCM 
I found this error in my logs:
[main/WARN]: Warnings were found!
 - Mod 'CIT Resewn: Defaults' (citresewn-defaults) 1.0.1+1.18.2 conflicts with any version of mod 'Eating Animation' (eatinganimationid), which is present with the following versions: 1.6!
	 - While this won't prevent you from starting the game, the developer(s) of mod 'CIT Resewn: Defaults' (citresewn-defaults) have found that this combination may cause issues. You should remove one of the mods or check for updates that resolve the issue.

@Theoness1 can you fix this since SHsuperCM (dev of CIT Resewn) suggested a workaround [several comments above](https://github.com/Theoness1/EatingAnimation/issues/9#issuecomment-975041306)
Also there is a pull request for this issue as well
thanks in advance <3

**Comment by magnus-ISU** [comment] 2022-06-29 23:02
For people who still want this, [here](https://github.com/Julienraptor01/EatingAnimation) is JulienRaptor01's fork which solves the issue. A binary can be downloaded [here](https://github.com/magnus-ISU/clientside-mods/blob/master/mods/eating-animation-1.8.1-beta.jar).

@JulienRaptor01 can you make a new PR? I would but there are apparently some other changes you made in your fork which maybe are not needed.

**Comment by Julienraptor01** [comment] 2022-06-29 23:08
> For people who still want this, [here](https://github.com/Julienraptor01/EatingAnimation) is JulienRaptor01's fork which solves the issue. A binary can be downloaded [here](https://github.com/magnus-ISU/clientside-mods/blob/master/mods/eating-animation-1.8.1-beta.jar).
> 
> @JulienRaptor01 can you make a new PR? I would but there are apparently some other changes you made in your fork which maybe are not needed.

Why do you link your redistribution of my build instead of just linking my [release](https://github.com/Julienraptor01/EatingAnimation/releases/download/v1.8.1-beta/eating-animation-1.8.1-beta.jar) ? 

Why should i make a new PR ? This PR is fine currently. (it's not perfect and Theoness1 is looking at a better fix)

My fork don't change this fix. My fork is an addition of this CIT fix + my compatibility pack for VTSU integrated in the mod.

**Comment by Theoness1** [comment] 2022-07-21 19:36
fixed soon

**Closed by Theoness1** 2022-07-21 19:36 UTC
