### ISSUE TITLE
EatingAnimations Breaks tool and weapon textures in Visual Enchantments Resource Pack

### ISSUE THREAD

**Issue by AlfmanOO7** [Theoness1/EatingAnimation#20] opened 2022-05-10 11:02 UTC
![image](https://user-images.githubusercontent.com/62825044/167614188-6facb206-1f5c-4b94-b038-c5cb1311b1b8.png)
Tools and Weapons should be textured differently to vanilla textures
Pack: https://www.curseforge.com/minecraft/texture-packs/visual-enchantments

**Comment by Theoness1** [comment] 2022-05-29 13:47
Yo, oops.

hmm i'll try to figure it out

**Comment by Julienraptor01** [comment] 2022-05-29 14:39
This pack needs CIT so https://github.com/Theoness1/EatingAnimation/pull/16 to work (or another fix if you have another one)
This is a duplicate of #9

**Comment by Theoness1** [comment] 2022-07-21 19:36
fixed soon

**Closed by Theoness1** 2022-07-21 19:36 UTC
